test_that('mdl_to_ndat works properly without "cond".', {
	tgt <- c('x0','x1')
	ndat <- mdl_to_ndat(mdl=tmdl0, target=tgt, len=10, method=median)
	expect_s3_class(ndat, 'data.frame')
	expect_equal(colnames(ndat), c('x0','fac','x1','x2'))
	expect_equal(nrow(ndat), 100)
	expect_length(unique(ndat$x0), 10)
	expect_length(unique(ndat$x1), 10)
	expect_length(unique(ndat$x2),  1)
	expect_length(unique(ndat$fac),  1)
	expect_equal(round(mean(ndat$x0),5), 0.50298)
	expect_equal(round(mean(ndat$x1),5), 0.49812)
	expect_equal(round(mean(ndat$x2),5), 0.50012)
})
test_that('mdl_to_ndat works properly with "cond".', {
	tgt <- c('x0','x1')
	clist <- list('x0'=10,'x1'=c(20,30),'x2'=c(40,50))
	ndat <- mdl_to_ndat(mdl=tmdl0, target=tgt, cond=clist,
			    len=10, method=median)
	expect_s3_class(ndat, 'data.frame')
	expect_equal(colnames(ndat), c('x0','fac','x1','x2'))
	expect_equal(ndat$x0, rep(10,4))
	expect_equal(ndat$x1, rep(c(20,30),2))
	expect_equal(ndat$x2, rep(c(40,50),each=2))
})
test_that('mdl_to_ndat works with "cond" for only a subset of variables.', {
	tgt <- c('x0','x1')
	clist <- list('x1'=c(20,30))
	ndat <- mdl_to_ndat(mdl=tmdl0, target=tgt, cond=clist,
			    len=10, method=median)
	expect_s3_class(ndat, 'data.frame')
	expect_equal(colnames(ndat), c('x0','fac','x1','x2'))
	expect_equal(nrow(ndat), 20)
	expect_length(unique(ndat$x0), 10)
	expect_length(unique(ndat$x1),  2)
	expect_length(unique(ndat$x2),  1)
	expect_equal(round(mean(ndat$x0),5), 0.50298)
	expect_equal(round(mean(ndat$x1),5),      25)
	expect_equal(round(mean(ndat$x2),5), 0.50012)
})
test_that('mdl_to_ndat works when the model has only one predictor', {
	tgt <- c('x0')
	ndat <- mdl_to_ndat(mdl=tmdl1, target=tgt, len=10, method=median)
	expect_s3_class(ndat, 'data.frame')
	expect_equal(colnames(ndat), c('x0'))
	expect_equal(nrow(ndat), 10)
	expect_length(unique(ndat$x0), 10)
	expect_equal(round(mean(ndat$x0),5), 0.50298)
})
test_that('mdl_to_ndat, add_fit, and ndat_to_contour
	  produces the same as plot_contour.', {
	tgt <- c('x0','x1')
	cnd <- list(fac='1')
	ndat <- mdl_to_ndat(mdl=tmdl0, target=tgt, cond=cnd,
			    len=50, method=median)
	ndat <- add_fit(ndat, tmdl0, terms=tgt, cond=cnd, ci.mult=1,
			verbose=FALSE)
	plt0 <- ndat_to_contour(ndat, x=tgt[1], y=tgt[2],
				z='fit', zlim=NULL)
	plt1 <- plot_contour(tmdl0, view=tgt, cond=cnd, summed=FALSE, zlim=NULL)
	gtypes0 <- vapply(plt0$layers,
			  function(x) class(x$geom)[1],
			  character(1))
	gtypes1 <- vapply(plt1$layers,
			  function(x) class(x$geom)[1],
			  character(1))
	expect_s3_class(plt0, 'ggplot')
	expect_s3_class(plt1, 'ggplot')
	expect_match(gtypes0[1], 'GeomPolygon', fixed=TRUE)
	expect_match(gtypes0[2], 'GeomContour', fixed=TRUE)
	expect_match(gtypes0[3], 'GeomTextContour', fixed=TRUE)
	expect_match(gtypes1[1], 'GeomPolygon', fixed=TRUE)
	expect_match(gtypes1[2], 'GeomContour', fixed=TRUE)
	expect_match(gtypes1[3], 'GeomTextContour', fixed=TRUE)
	scl0 <- layer_scales(plt0)
	scl1 <- layer_scales(plt1)
	expect_equal(round(scl0$x$range$range[1],7), 0.0066501)
	expect_equal(round(scl0$x$range$range[2],7), 0.9993194)
	expect_equal(round(scl0$y$range$range[1],7), 0.0013797)
	expect_equal(round(scl0$y$range$range[2],7), 0.9948520)
	expect_equal(round(scl1$x$range$range[1],7), 0.0066501)
	expect_equal(round(scl1$x$range$range[2],7), 0.9993194)
	expect_equal(round(scl1$y$range$range[1],7), 0.0013797)
	expect_equal(round(scl1$y$range$range[2],7), 0.9948520)
})
